import { DEFAULT_DARK_THEME, type TuiTheme } from "@may/tui";

/** MaybeCode's restrained dark palette. Applications may replace it later. */
export const MAYBECODE_DARK_THEME: TuiTheme = {
  ...DEFAULT_DARK_THEME,
  name: "maybecode-dark",
  accent: { foreground: "#7dd3fc", bold: true },
  muted: { foreground: "#94a3b8" },
  dim: { foreground: "#64748b" },
  success: { foreground: "#86efac" },
  warning: { foreground: "#fde047" },
  error: { foreground: "#fb7185" },
  border: { foreground: "#475569" },
  borderAccent: { foreground: "#38bdf8" },
  selected: { foreground: "#f8fafc", background: "#1e3a5f", bold: true },
  userMessage: { foreground: "#f8fafc", bold: true },
  assistantLabel: { foreground: "#7dd3fc", bold: true },
  thinking: { foreground: "#94a3b8", italic: true },
  toolTitle: { foreground: "#93c5fd", bold: true },
  toolOutput: { foreground: "#e2e8f0" },
  toolPending: { foreground: "#fde047" },
  toolSuccess: { foreground: "#86efac" },
  toolError: { foreground: "#fb7185" },
  diffAdded: { foreground: "#86efac" },
  diffRemoved: { foreground: "#fda4af" },
  diffContext: { foreground: "#94a3b8" },
  markdown: {
    heading: { foreground: "#7dd3fc", bold: true },
    link: { foreground: "#93c5fd", underline: true },
    linkUrl: { foreground: "#64748b" },
    code: { foreground: "#fde68a" },
    codeBlock: { foreground: "#e2e8f0" },
    codeBlockBorder: { foreground: "#475569" },
    quote: { foreground: "#cbd5e1", italic: true },
    quoteBorder: { foreground: "#38bdf8" },
    horizontalRule: { foreground: "#475569" },
    listBullet: { foreground: "#38bdf8" },
  },
};
