import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { McpTaskJournal, InMemoryMcpCredentialStore, KeyringMcpCredentialStore, McpInteractionBroker, openMcpClientPool } from "../dist/index.js";
import { startTaskServer } from "./fixtures/task-server.mjs";

const owner = { workspaceId: "workspace", sessionId: "session" };
const context = (signal = new AbortController().signal) => ({ scope: owner, signal, runId: "origin-run", toolCallId: "origin-call", step: 1, idempotencyKey: "call", report() {} });
const nextQuestion = (broker) => { const events = broker.events[Symbol.asyncIterator](); return async () => { for (;;) { const event = (await events.next()).value; if (event.type === "mcp.interaction.requested" && broker.list(owner).some((r) => r.id === event.request.id)) return event.request; } }; };

test("task calls negotiate native frames, persist handles, fulfill reviewed inputs and distinguish local wait from remote cancel", { timeout: 15_000 }, async (t) => {
  const fixture = await startTaskServer(t);
  const taskJournal = new McpTaskJournal(new InMemoryMcpCredentialStore());
  let broker = new McpInteractionBroker();
  const server = { id: "jobs", transport: "streamable-http", url: fixture.url, tasks: true, host: { sampling: true }, requestTimeoutMs: 1000 };
  const calls = [];
  const open = () => openMcpClientPool({ servers: [server], taskJournal, interactions: broker, hostServices: { sampling: { async createMessage(params, context) { calls.push({ params, context }); return { role: "assistant", model: "isolated-model", content: { type: "text", text: "review-before-share" } }; } } } });
  let pool = await open(); t.after(() => pool.close());
  fixture.state.before = true; fixture.state.input = true;
  let next = nextQuestion(broker);
  const start = pool.tools[0].execute({ route: "北京" }, context());
  let question = await next(); assert.equal(question.owner.runId, "origin-run");
  broker.respond(question.id, question.owner, { action: "accept", content: { value: "pre-creation answer" } });
  const output = await start;
  const [record] = await pool.listTasks(owner);
  assert.ok(output.content[0].text.includes(record.id)); assert.equal(record.status, "input_required");
  assert.equal(record.initialUsage.inputs, 1);
  assert.equal(fixture.state.calls, 1);
  assert.ok(fixture.requests.filter((r) => r.message.method === "tools/call").every((r) => r.headers["mcp-param-route"] === "=?base64?5YyX5Lqs?="));
  await pool.close(); broker = new McpInteractionBroker(); pool = await open(); next = nextQuestion(broker);
  const requestsBefore = fixture.requests.length;
  assert.equal((await pool.listTasks(owner))[0].id, record.id);
  assert.equal(fixture.requests.length, requestsBefore, "local recovery must not poll or replay");
  await assert.rejects(pool.getTask("jobs", record.id, { owner: { ...owner, sessionId: "wrong" } }), /not owned/u);
  assert.equal(fixture.requests.length, requestsBefore);
  const pending = pool.updateTask("jobs", record.id, { owner });
  question = await next(); assert.equal(question.owner.runId, "origin-run");
  broker.respond(question.id, question.owner, { action: "accept", content: { value: "task answer" } });
  question = await next(); assert.equal(question.params.kind, "sampling.request"); assert.equal(calls.length, 0);
  broker.respond(question.id, question.owner, { action: "accept" });
  question = await next(); assert.equal(question.params.kind, "sampling.response");
  assert.equal(fixture.state.updates.length, 1, "model output must be withheld until review");
  broker.respond(question.id, question.owner, { action: "accept" });
  const completed = await pending;
  assert.equal(completed.state.status, "completed"); assert.equal(completed.record.samplingCalls, 1);
  assert.equal(calls[0].params.messages[0].content.text, "Task-only input");
  for (const rpc of fixture.requests.filter((r) => r.message.method.startsWith("tasks/"))) assert.equal(rpc.headers["mcp-name"], rpc.message.params.taskId);
  assert.doesNotMatch(JSON.stringify(await pool.listTasks(owner)), /task answer|review-before-share|Task-only input/u);

  fixture.state.before = false; fixture.state.input = false;
  await pool.tools[0].execute({}, context());
  const working = (await pool.listTasks(owner)).find((r) => r.status === "working");
  const abort = new AbortController();
  const waiting = pool.waitTask("jobs", working.id, { owner, signal: abort.signal, timeoutMs: 1000 });
  setTimeout(() => abort.abort(), 40);
  await assert.rejects(waiting); assert.deepEqual(fixture.state.cancels, []);
  const intent = await pool.cancelTask("jobs", working.id, { owner });
  assert.equal(intent.status, "working"); assert.equal(intent.cancellation, "acknowledged");
  fixture.state.tasks[working.remote.taskId].status = "completed";
  fixture.state.tasks[working.remote.taskId].result = { content: [{ type: "text", text: "cancel lost completion race" }] };
  assert.equal((await pool.getTask("jobs", working.id, { owner })).state.status, "completed");
  await pool.forgetTask("jobs", working.id, owner);
  assert.equal((await pool.listTasks(owner)).length, 1);

  // Withholding a sampling response consumes usage but permits an explicitly
  // requested, freshly reviewed recovery; ordinary update never repeats it.
  fixture.state.input = true;
  await pool.tools[0].execute({}, context());
  const retry = (await pool.listTasks(owner)).find((r) => r.status === "input_required");
  delete fixture.state.tasks[retry.remote.taskId].inputRequests.form;
  const withheld = pool.updateTask("jobs", retry.id, { owner });
  question = await next(); broker.respond(question.id, question.owner, { action: "accept" });
  question = await next(); broker.respond(question.id, question.owner, { action: "decline" });
  await assert.rejects(withheld, /withheld/u);
  await assert.rejects(pool.updateTask("jobs", retry.id, { owner }), /already claimed/u);
  await pool.close(); broker = new McpInteractionBroker(); pool = await open(); next = nextQuestion(broker);
  const recovering = pool.updateTask("jobs", retry.id, { owner, retryAbandonedInputs: true });
  question = await next(); broker.respond(question.id, question.owner, { action: "accept" });
  question = await next(); broker.respond(question.id, question.owner, { action: "accept" });
  const recovered = await recovering;
  assert.equal(recovered.state.status, "completed"); assert.equal(recovered.record.samplingCalls, 2);
  assert.equal(recovered.record.inputAttempts, 2);
  assert.equal(fixture.state.calls, 3, "input recovery must never replay original tools/call");
});

test("stdio task handles recover across process restart and fail closed on changed definitions, bad results and unknown calls", { timeout: 15_000 }, async (t) => {
  const directory = await mkdtemp(join(tmpdir(), "may-tasks-runtime-")); t.after(() => rm(directory, { recursive: true, force: true }));
  let password; const keyring = { getPassword: async () => password, setPassword: async (value) => { password = value; } };
  const journal = () => new McpTaskJournal(new KeyringMcpCredentialStore(join(directory, "journal"), keyring));
  const peerState = join(directory, "peer.json");
  const server = { id: "stdio", command: process.execPath, args: [fileURLToPath(new URL("./fixtures/task-server.mjs", import.meta.url)), "--stdio", peerState], protocolMode: "auto", tasks: true, requestTimeoutMs: 1000 };
  let pool = await openMcpClientPool({ servers: [server], taskJournal: journal() }); t.after(() => pool.close());
  await pool.tools[0].execute({}, context());
  const [record] = await pool.listTasks(owner); await pool.close();
  pool = await openMcpClientPool({ servers: [server], taskJournal: journal() });
  assert.equal((await pool.getTask("stdio", record.id, { owner })).state.status, "working");
  assert.equal(JSON.parse(await readFile(peerState, "utf8")).calls, 1);
  await pool.close();

  const fixture = await startTaskServer(t);
  const settings = { id: "http", transport: "streamable-http", url: fixture.url, tasks: true, requestTimeoutMs: 50 };
  pool = await openMcpClientPool({ servers: [settings], taskJournal: journal() });
  await pool.tools[0].execute({}, context());
  const remote = (await pool.listTasks(owner)).find((r) => r.binding.serverId === "http");
  fixture.state.version++;
  await pool.refresh("http");
  const count = fixture.requests.length;
  await assert.rejects(pool.getTask("http", remote.id, { owner }), /not owned/u);
  assert.equal(fixture.requests.length, count);
  fixture.state.outputSchema = { type: "object", properties: { value: { type: "string" } }, required: ["value"] };
  await pool.refresh("http");
  await pool.tools[0].execute({}, context());
  const invalid = (await pool.listTasks(owner)).find((r) => r.binding.serverId === "http" && r.id !== remote.id);
  fixture.state.tasks[invalid.remote.taskId].status = "completed";
  fixture.state.tasks[invalid.remote.taskId].result = { content: [], structuredContent: { wrong: true } };
  await assert.rejects(pool.getTask("http", invalid.id, { owner }), /output schema/u);
  assert.equal((await pool.listTasks(owner)).find((r) => r.id === invalid.id).status, "working");
  fixture.state.tasks[invalid.remote.taskId].result = { content: [{ type: "text", text: "reported tool failure" }], isError: true };
  assert.equal((await pool.getTask("http", invalid.id, { owner })).state.result.isError, true);
  fixture.state.hold = true;
  await assert.rejects(pool.tools[0].execute({}, context()), /timeout/u);
  assert.ok((await pool.listTasks(owner)).some((r) => r.status === "uncertain"));
  await assert.rejects(openMcpClientPool({ servers: [settings] }), /journal/u);
  await pool.close();
  pool = await openMcpClientPool({ servers: [{ ...settings, headers: { Authorization: "Bearer new-principal" } }], taskJournal: journal() });
  const authBefore = fixture.requests.length;
  await assert.rejects(pool.getTask("http", invalid.id, { owner }), /not owned/u);
  assert.equal(fixture.requests.length, authBefore);
});
