packages:
  - "packages/*"
  - "packages/providers/*"
  - "packages/plugins/*"
  - "packages/tools/*"
  - "packages/ui/*"
  - "apps/*"
  - "examples/*"
allowBuilds:
  protobufjs: false
  sharp: true
patchedDependencies:
  vscode-jsonrpc@9.0.2: patches/vscode-jsonrpc@9.0.2.patch
