import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { createSkillsPlugin } from "../dist/index.js";
import { PluginHost } from "../../../plugin/dist/index.js";
import { services, ToolSources, InstructionSources } from "../../../plugin-services/dist/index.js";
import { SkillRegistry } from "../../../skills/dist/index.js";

test("Skills plugin activates actual skill files, persists state and restores an independent instance", async t => {
  const destination = fileURLToPath(new URL("../../../../plugin-verification/", import.meta.url));
  await mkdir(destination, { recursive: true });
  const directory = await mkdtemp(join(destination, "skills-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await mkdir(join(directory, "verification"));
  await writeFile(join(directory, "verification", "SKILL.md"), "---\nname: verification\ndescription: Read verification files\n---\nRead the actual documentation.");
  const registry = await SkillRegistry.discover([directory]);
  const plugin = createSkillsPlugin({ create: () => registry });
  const tools = new ToolSources(), instructions = new InstructionSources();
  instructions.add(() => "# Current environment\n\nWorkspace: " + directory, { id: "environment", order: -80 });
  instructions.add(() => "# Context continuity", { id: "continuity", order: 60 });
  const host = await PluginHost.create({ plugins: [plugin], services: [{ service: services.toolSources, value: tools }, { service: services.instructionSources, value: instructions }] });
  t.after(() => host.close());
  const scope = await host.createScope("application", { id: "first" });
  const initial = instructions.snapshot();
  assert.match(initial, /Read verification files/u);
  assert.doesNotMatch(initial, /Read the actual documentation/u);
  assert.ok(initial.indexOf("# Current environment") < initial.indexOf("# Available skills"));
  assert.ok(initial.indexOf("# Available skills") < initial.indexOf("# Context continuity"));
  await scope.get(services.skills).activate("verification");
  assert.match(instructions.snapshot(), /Read the actual documentation/);
  assert.equal(tools.snapshot().require("skill_read").name, "skill_read");
  const state = scope.snapshotState();
  await scope.close();
  assert.equal(tools.snapshot().size, 0);
  assert.doesNotMatch(instructions.snapshot(), /# Available skills|# Active skills/u);
  await writeFile(join(directory, "verification", "SKILL.md"), "---\nname: verification\ndescription: Read verification files\n---\nUpdated instructions.");
  const resumed = await host.createScope("application", { id: "resumed", state });
  assert.equal(resumed.get(services.skills).listActive()[0].name, "verification");
  assert.match(instructions.snapshot(), /Read the actual documentation/u);
  assert.doesNotMatch(instructions.snapshot(), /Updated instructions/u);
  assert.notEqual(resumed.get(services.skills), scope);
});
