import assert from "node:assert/strict";
import { mkdir, mkdtemp } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { PassThrough } from "node:stream";
import test from "node:test";
import { FileMediaStore } from "@may/media";
import { imageSource } from "../../../media/test/fixture.mjs";
import { TerminalImages, FullscreenRenderer, Stack, ScrollView, Text, TranscriptStore, TranscriptView } from "../dist/index.js";

test("真实图片的 Terminal 布局、滚动、清除及纯文本输出", async () => {
  const base = fileURLToPath(new URL("../../../../review/media-tests/", import.meta.url));
  await mkdir(base, { recursive: true });
  const source = await imageSource(), media = new FileMediaStore(await mkdtemp(join(base, "terminal-")));
  const images = new TerminalImages(media, "kitty");
  await images.prepare([{ type: "image", source }]);
  const view = new Stack([new Text("before"), images.component(source), new Text("after")]);
  const rendered = view.render({ width: 80, height: 40 });
  assert.equal(rendered.images.length, 1);
  assert.ok(rendered.images[0].y > rendered.lines.indexOf("before"));
  assert.ok(rendered.lines.indexOf("after") >= rendered.images[0].y + rendered.images[0].rows);
  const output = new PassThrough(); output.setEncoding("utf8");
  const renderer = new FullscreenRenderer(output);
  renderer.render(rendered, { width: 80, height: 40 });
  assert.match(output.read(), /\x1b_Ga=T/);
  renderer.render({ lines: ["dialog"] }, { width: 80, height: 40 });
  assert.match(output.read(), /\x1b_Ga=d/);
  const scroll = new ScrollView(view);
  const clipped = scroll.render({ width: 80, height: 5 });
  assert.ok(!clipped.images?.length);
  const textImages = new TerminalImages(media, "none"); await textImages.prepare([{ type: "image", source }]);
  const text = textImages.render(source, { width: 180, height: 10 });
  assert.match(text.lines.join("\n"), /64×32/); assert.match(text.lines.join("\n"), /\.png/); assert.equal(text.images, undefined);
  const store = new TranscriptStore();
  const message = { role: "assistant", content: [{ type: "image", source }] };
  store.applyMayEvent({ type: "model.completed", seq: 1, runId: "image", step: 1, timestamp: 1, message });
  store.applyMayEvent({ type: "run.completed", seq: 2, runId: "image", timestamp: 2, result: { message, steps: 1 } });
  assert.ok(store.latestReply);
  const transcript = new TranscriptView(store, { images });
  transcript.revealLatestReply();
  assert.equal(transcript.renderTail({ width: 80, height: 40 }).images.length, 1);
  assert.ok(transcript.latestReplyAnchor);
});
